name: poweron

services:
  bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: poweron-app:latest
    container_name: poweron-bot
    command: ["php", "bin/console", "app:bot"]
    env_file:
      - ../.env
      - ../.env.dev
      - ../.env.local
    volumes:
      - ../data:/app/data
    restart: unless-stopped

  notifier:
    image: poweron-app:latest
    depends_on:
      - bot
    container_name: poweron-notifier
    command: ["/app/docker/docker-entrypoint-cron.sh"]
    env_file:
      - ../.env
      - ../.env.dev
      - ../.env.local
    volumes:
      - ../data:/app/data
    restart: unless-stopped
